version: "3"
services:
  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=alquilame
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
  
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - 5050:80 
  
  api:
    image: api:1.0
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  web:
    image: web:1.0
    container_name: web
    ports:
     - 80:80
    depends_on:
      - api

