version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=alquilame
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"
  
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
  
  api:
    container_name: api
    build: ./api/Alquilame
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/alquilame
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
  
  web:
    container_name: web
    build: ./web/Alquilame
    restart: always
    ports:
     - 4200:80
    environment:
      - API_BASE_URL=http://localhost:8080

