// Generated by https://quicktype.io

export interface AllUserResponse {
  content:       User[];
  totalElements: number;
  totalPages:    number;
  number:        number;
  size:          number;
}

export interface User {
  id:              string;
  username:        string;
  avatar:          string;
  fullName:        string;
  address:         string;
  email:           string;
  role:            Role;
  phoneNumber:     string;
  numPublications: number;
  createdAt:       string;
}

export enum Role {
  Inquilino = "INQUILINO",
  Propietario = "PROPIETARIO",
  Admin = "ADMIN"
}
